version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"  # Expose Redis on default port
    volumes:
      - redis-data:/data  # Persist Redis data on the host machine
    restart: always  # Automatically restart the container if it stops
    networks:
      - redis-network

volumes:
  redis-data:
    driver: local  # Uses local volume driver to persist data

networks:
  redis-network:
    driver: bridge  # Use a bridge network for internal communication
